from pathlib import Path

def replace(p,a,b):
    f=Path(p); s=f.read_text(); assert s.count(a)==1, (p,a[:90],s.count(a)); f.write_text(s.replace(a,b))
k='runtime/vnext/src/kernel.ts'
replace(k, "    if (!options.dryRun && !exists) executeWrites([{ path: location.filePath, content }], false, 'Prepare evidence-plan amendment candidate only');", "    if (!options.dryRun && !exists) {\n      fs.mkdirSync(path.dirname(location.filePath), { recursive: true });\n      executeWrites([{ path: location.filePath, content }], false, 'Prepare evidence-plan amendment candidate only');\n    }")
replace(k, "    const prefix = `evidence-amend-${receipt.candidate_digest}-`;", "    if (receipt.document_id !== current.sourceTuple.document_id || receipt.task_id !== current.runtimeState.task_id) fail('EVIDENCE_AMENDMENT_IDENTITY_CONFLICT', 'The candidate belongs to another task.');\n    const prefix = `evidence-amend-${receipt.candidate_digest}-`;")
t='test/vnext-runtime.test.ts'
replace(t, "      const fingerprint = 'evidence-amendment-retained-finding';", "      // Fingerprint is owned by the public review adapter, not caller input.")
replace(t, "findings: [{ fingerprint, category: 'correctness', file: 'README.md', failure_condition: 'The admitted observation remains unsatisfied.',", "findings: [{ category: 'correctness', file: 'README.md', failure_condition: 'The admitted observation remains unsatisfied.',")
replace(t, "      expect(submitAmendmentExecution(root, beginRepair(root, { candidate_paths: ['README.md'] })).status).toBe('success');", "      const fingerprint = readCanonicalCurrentTask(root).runtimeState.pending_review_result!.findings[0]!.fingerprint;\n      expect(submitAmendmentExecution(root, beginRepair(root, { candidate_paths: ['README.md'] })).status).toBe('success');")
f=Path('docs/designs/workflow-vnext-target-architecture.md')
s=f.read_text(); marker='Public Skills return recommendations rather than invoking the next public Skill automatically.'
assert s.count(marker)==1
s=s.replace(marker, 'An explicitly authorized evidence-selection amendment under unchanged Goal, Acceptance, observation boundary and total authority has its own same-task prepare/confirm path. It does not require a previous report or challenge, a new business requirement, or supersede. Pending findings and recorded repair history remain owned by the current task; changed checks require new results, and an affected clean review remains historical rather than proving the replacement selection. '+marker)
f.write_text(s)
replace('runtime/vnext/src/kernel.ts', '  command_replacements: Array<{ step_id: string; old_command: string; new_commands: string[] }>;\n};', '  command_replacements: Array<{ step_id: string; old_command: string; new_commands: string[] }>;\n  validation_replacements?: Array<{ step_id: string; old_validation: string; new_validation: string; check_ids: string[]; reason: string }>;\n};')
replace('runtime/vnext/src/kernel.ts', "expectExactKeys(input, ['source_revision', 'decision_source', 'decision_text', 'reason', 'replacements', 'command_replacements'], 'evidence-plan amendment');", "expectExactKeys(input, ['source_revision', 'decision_source', 'decision_text', 'reason', 'replacements', 'command_replacements', ...(input.validation_replacements === undefined ? [] : ['validation_replacements'])], 'evidence-plan amendment');")
replace('runtime/vnext/src/kernel.ts', "  return { source_revision: expectString(input.source_revision, 'source_revision', SHA256_PATTERN),\n    decision_source: expectText(input.decision_source, 'decision_source', 1024),", "  const validations = input.validation_replacements;\n  if (validations !== undefined && (!Array.isArray(validations) || validations.length > MAX_EXECUTION_RESULT_ITEMS)) fail('EVIDENCE_AMENDMENT_INVALID', 'Validation description changes must be bounded.');\n  const validationChanges = (validations as unknown[] | undefined)?.map(raw => {\n    const row = expectRecord(raw, 'validation replacement');\n    expectExactKeys(row, ['step_id', 'old_validation', 'new_validation', 'check_ids', 'reason'], 'validation replacement');\n    const oldLabel = expectText(row.old_validation, 'old_validation', 4096);\n    const newLabel = expectText(row.new_validation, 'new_validation', 4096);\n    const ids = expectStringArray(row.check_ids, 'check_ids', false, MAX_CLAIM_EVIDENCE_RECORDS).map(id => expectString(id, 'check_id', CLAIM_ID_PATTERN));\n    if (/[;\\r\\n]/u.test(oldLabel + newLabel) || oldLabel === newLabel || new Set(ids).size !== ids.length) fail('EVIDENCE_AMENDMENT_INVALID', 'Selection descriptions need changed single-line labels and unique old check IDs.');\n    return { step_id: expectString(row.step_id, 'step_id', STEP_ID_PATTERN), old_validation: oldLabel, new_validation: newLabel, check_ids: ids, reason: expectText(row.reason, 'validation replacement reason') };\n  });\n  if (validationChanges && new Set(validationChanges.map(row => `${row.step_id}\\0${row.old_validation}`)).size !== validationChanges.length) fail('EVIDENCE_AMENDMENT_INVALID', 'Each validation label may be rebound only once.');\n  return { ...(validationChanges === undefined ? {} : { validation_replacements: validationChanges }), source_revision: expectString(input.source_revision, 'source_revision', SHA256_PATTERN),\n    decision_source: expectText(input.decision_source, 'decision_source', 1024),")
replace('runtime/vnext/src/kernel.ts', '      allowed_substitutes: value.allowed_substitutes, validation_items: value.validation_items });\n    if (digest(obligation(old)) !== digest(obligation(check)))', '      allowed_substitutes: value.allowed_substitutes, validation_items: value.validation_items });\n    const oldWithReboundLabels = { ...old, ...(old.validation_items === undefined ? {} : { validation_items: old.validation_items.map(label => (input.validation_replacements ?? []).find(change => change.step_id === slot.due_step_id && change.old_validation === label && change.check_ids.includes(old.check_id))?.new_validation ?? label) }) };\n    if (digest(obligation(oldWithReboundLabels)) !== digest(obligation(check)))')
replace('runtime/vnext/src/kernel.ts', '  // Past results remain tied to their immutable preimage. A new invocation\n', "  for (const row of input.validation_replacements ?? []) {\n    const oldStep = steps.find(step => step.id === row.step_id);\n    if (!oldStep || steps.indexOf(oldStep) < currentIndex) fail('EVIDENCE_AMENDMENT_STEP_INVALID', 'Only current/future selection descriptions may change.');\n    for (const checkId of row.check_ids) {\n      const replacement = input.replacements.find(change => change.replaces_check_id === checkId);\n      const oldSlot = oldClaims.flatMap(claim => claim.slots).find(slot => slot.check?.check_id === checkId);\n      const command = input.command_replacements.find(change => change.step_id === row.step_id && change.old_command === oldSlot?.check?.entry);\n      if (!replacement || !oldSlot?.check || !command || !command.new_commands.includes(replacement.replacement_check.entry)\n        || (oldSlot.check.validation_items !== undefined && (!oldSlot.check.validation_items.includes(row.old_validation) || oldSlot.due_step_id !== row.step_id))) fail('EVIDENCE_AMENDMENT_VALIDATION_UNBOUND', 'A changed description must name the selected check and its exact step invocation; an explicitly owned label cannot be reassigned.');\n    }\n    const owners = oldClaims.flatMap(claim => claim.slots).filter(slot => slot.due_step_id === row.step_id && slot.check?.validation_items?.includes(row.old_validation));\n    if (owners.some(slot => !row.check_ids.includes(slot.check!.check_id))) fail('EVIDENCE_AMENDMENT_VALIDATION_UNBOUND', 'A shared validation description must retain every independently bound owner.');\n    const block = implementationStepBlock(definition, row.step_id)!;\n    const lines = block.split('\\n');\n    const labelIndex = lines.findIndex(line => /^\\s*- required_evidence:/.test(line));\n    if (labelIndex < 0) fail('EVIDENCE_AMENDMENT_VALIDATION_UNBOUND', 'The selected validation labels are absent.');\n    const labels = lines[labelIndex]!.replace(/^\\s*- required_evidence:\\s*/u, '').split(';').map(label => label.trim()).filter(Boolean);\n    if (labels.filter(label => label === row.old_validation).length !== 1 || labels.includes(row.new_validation)) fail('EVIDENCE_AMENDMENT_VALIDATION_UNBOUND', 'Replace one exact existing label without merging another obligation.');\n    lines[labelIndex] = '  - required_evidence: ' + labels.map(label => label === row.old_validation ? row.new_validation : label).join('; ');\n    definition.implementation_steps = definition.implementation_steps.replace(block, lines.join('\\n'));\n  }\n  // Past results remain tied to their immutable preimage. A new invocation\n")
replace('test/vnext-runtime.test.ts', "      const request = evidenceAmendmentRequest(root);\n      expect(prepareEvidencePlanAmendment(root, request, { dryRun: true }).status).toBe('success');", "      const request = { ...evidenceAmendmentRequest(root), validation_replacements: ['step-1', 'step-2'].map(step_id => ({\n        step_id, old_validation: 'bun test test/vnext-runtime.test.ts passes', new_validation: 'The explicitly selected necessary cases pass',\n        check_ids: ['K1'], reason: 'Replace only the invocation description; the frozen claim and observation are unchanged.' })) };\n      expect(prepareEvidencePlanAmendment(root, request, { dryRun: true }).status).toBe('success');")
replace('test/vnext-runtime.test.ts', "      expect(nextRepair.current_step.commands.some(item => item.command.includes('--test-name-pattern exact-case'))).toBe(true);", "      expect(nextRepair.current_step.commands.some(item => item.command.includes('--test-name-pattern exact-case'))).toBe(true);\n      expect(nextRepair.current_step.validation).toEqual(['The explicitly selected necessary cases pass']);")

for name in ['runtime/vnext/support/CONTEXT_API.md','templates/vnext/skills/prepare-task.SKILL.md.tmpl','templates/vnext/skills/execute-step.SKILL.md.tmpl']:
    f=Path(name); text=f.read_text()
    if name.endswith('CONTEXT_API.md'):
        text=text.replace('Previous step history, validation observation labels, Persistent Tests admission,', 'Previous step history, independent validation obligations, Persistent Tests admission,')
        text += '''

Selection-dependent step descriptions may be rebound in the same candidate with
optional `validation_replacements: [{step_id, old_validation, new_validation,
check_ids, reason}]`. `check_ids` are the old IDs included in `replacements`, and
each must have its exact invocation changed in that step. Explicitly owned labels
retain all their owners, including the corresponding replacement check's
`validation_items`; legacy unowned descriptions do not gain waiver ownership.
Only descriptions of the changed selection may be revised, not an independent
behavioral requirement. The Agent must justify that distinction and the user
confirms the exact old/new text. Runtime verifies the structural ownership and
keeps every frozen claim observation/boundary unchanged; semantic sufficiency is
caller-reported, not inferred from label text or a green aggregate command.
'''
    else:
        text += '''
When a frozen step label still names the former whole-suite invocation, include
its selection-only `validation_replacements` in the same candidate instead of
claiming the old suite ran. Bind the old check IDs, preserve independent behavior
requirements and label ownership, and show the exact before/after description to
the user. Do not treat a selector rename as a waiver of a business obligation.
'''
    f.write_text(text)
